# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('categoria_post', models.CharField(choices=[(b'BUENOS EJEMPLOS', b'Buenos Ejemplos'), (b'URBANISMO Y VIALIDAD', b'Urbanismo Y Vialidad'), (b'NEGOCIOS', b'Negocios'), (b'SOCIAL', b'Social'), (b'GOBIERNO', b'Gobierno'), (b'SERVICIO COMUNITARIO', b'Servicio a la comunidad'), (b'OBJETOS PERDIDOS', b'Objetos Perdidos')], default=b'Social', max_length=20)),
                ('contenido', models.TextField()),
                ('media', models.ImageField(blank=True, null=True, upload_to=b'post_media/')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicacion', models.DateTimeField(blank=True, null=True)),
                ('Slug', models.SlugField(max_length=200, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
